### ISSUE TITLE
"No route for that URI"

### ISSUE THREAD

**Issue by selfagency** [cloudflare/serverless-cloudflare-workers#32]
When attempting to deploy, I get an error:

```
Serverless: ❌  Fatal Error, Script Not Deployed!
Serverless: --> Error Code:7000
--> Error Message: "No route for that URI"
```

I can confirm that my environment variables are properly set. As I understand it, "No route for that URI" is the response Cloudflare gives when you attempt to reach a non-existent API endpoint. I tried to manually request every endpoint in your script but I didn't get a 7000 response on any of them, so I was unable to isolate the culprit.

My `serverless.yml`:

```
service:
    name: kifa-micro

provider:
  name: cloudflare
  config:
    accountId: $CLOUDFLARE_ACCOUNT_ID
    zoneId: $CLOUDFLARE_ZONE_ID

plugins:
  - serverless-cloudflare-workers

functions:
  img:
    name: img
    script: fn/imgConv.js
    events:
      - http:
          url: api-kifa.kansasinterfaithaction.org/img
          method: GET
          headers:
            x-client-data: value
```
