### ISSUE TITLE
Documentation config missmatch

### ISSUE THREAD

**Issue by alexcroox** [cloudflare/serverless-cloudflare-workers#63]
Documentation states:

```
service:
  name: service-name
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
```

but `serverless create --template cloudflare-workers` generates:

```
service: projects

frameworkVersion: '2'

provider:
  name: cloudflare
  config:
    accountId: CLOUDFLARE_ACCOUNT_ID
    zoneId: CLOUDFLARE_ZONE_ID
```

Where is the config supposed to go?
