### ISSUE TITLE
Authentication Error When Deploying Cloudflare Worker with Valid Credentials

### ISSUE THREAD

**Issue by Paw-liblab** [cloudflare/serverless-cloudflare-workers#78]
#### Description:

I am encountering an authentication error when attempting to deploy a Cloudflare Worker using the Serverless Framework with the `serverless-cloudflare-workers` plugin. The error occurs despite the fact that the credentials are valid and have been successfully tested with a direct `curl` request to the Cloudflare API.

Environment variables were defined following the [documentation](https://www.serverless.com/framework/docs/providers/cloudflare/guide/installation) guideline

```bash
export CLOUDFLARE_AUTH_KEY=YOUR_API_KEY_HERE
export CLOUDFLARE_AUTH_EMAIL=YOUR_CLOUDFLARE_EMAIL
```

#### Error Message:

```bash
Error:
'[{"code":10000,"message":"Authentication error"}]'
```

#### Steps to Reproduce:

1. Configure the `serverless.yml` file with valid Cloudflare credentials (both global API key and user API tokens have been tested).
2. Run `serverless deploy`.
3. Observe the authentication error.

#### Expected Behavior:

The expected behavior is a successful deployment of the Cloudflare Worker without authentication errors.

#### Actual Behavior:

An authentication error is thrown, despite the credentials being valid and successfully tested with a direct API request.

#### Environment Information:

- Operating System: Linux
- Node.js Version: 18.17.1
- Serverless Framework Version: 3.34.0
- `serverless-cloudflare-workers` Plugin Version: 6.2.3

#### Serverless Configuration File:

```yaml
service: workers

frameworkVersion: '3'

provider:
  name: cloudflare
  config:
    accountId: XXX
    zoneId: XXX

functions:
  hello:
    name: hello
    script: helloWorld
    events:
      - http:
          url: XXX.com/*
          method: GET

plugins:
  - serverless-cloudflare-workers
```

#### Additional Information:

I have verified that the credentials are correct by successfully making a curl request to the Cloudflare API using the same email and API key. Both the global API key and user API tokens have been tested, and the issue persists.
